config/routes.rb
Kedvictor::Application.routes.draw do
   
  get "auth/index"

  root :to => "pages#index"
  
  mount Resque::Server, :at => "/resque"
  
  get "privat_gateway/index"
  post "privat_gateway/send_search_request"
  post "privat_gateway/send_bill_request" 
  
  get "auth/ident"
  get "test_mobile/index"
  
  
  get "tags/area"
  
  get "pages/resque"  
  get "pages/mouse"
  get "pages/widget"
  get "pages/http_request"  
  get "pages/xml_request"
  get "pages/except"
  
  post "pages/enqueue"
  post "test_mobile/send_request"
  
end

app/controllers/privat_gateway_controller.rb
class PrivatGatewayController < ApplicationController
  
  require 'net/http'
  require 'net/https'
  require "rexml/document" 
  
  PRIVAT_GATEWAY = "http://localhost:3000/payment/privatgate" 
  
  def index    
  end
  
  def send_search_request
    
    uri = URI( PRIVAT_GATEWAY )
    pars = {
      "action" => "bill_search",
      "bill_identifier" => params[:bill_identifier] }
         
    uri.query = URI.encode_www_form(pars)

    res = Net::HTTP.get_response uri    
    @response = res.body.force_encoding 'utf-8'     
    render :send_request
  end
  
  def send_bill_request
  
    uri = URI( PRIVAT_GATEWAY )
    pars = { 
      "action" => "bill_input", 
      "bill_identifier" => params[:bill_identifier],
      "sum" => params[:sum],
      "key" => params[:key],
      "date" => params[:date] } 
         
    uri.query = URI.encode_www_form(pars)

    res = Net::HTTP.get_response uri    
    @response = res.body.force_encoding 'utf-8'    
    render :send_request
  end
  
end

app/helpers/privat_gateway_helper.rb
module PrivatGatewayHelper
end

app/views/privat_gateway/_send_request.html.erb
<%= @response %>

app/views/privat_gateway/index.html.erb
<h3>Gateway Privat test on dev.2show.mobi</h3>

<fieldset id="search-request">
  <legend>Bill search request</legend>
  
  <%= form_tag( privat_gateway_send_search_request_path , 
    :remote => true) do %>
  
    <p>bill_identifier: 
      <%= text_field_tag :bill_identifier, "121212", :size => 10 %>
      <%= submit_tag "Send search request" %>
    </p>  
  
  <% end %>
  
</fieldset>

<fieldset id="bill-request">
  <legend>Bill input request</legend>
  
  <%= form_tag( privat_gateway_send_bill_request_path , 
    :remote => true) do %>
  
    <p>bill_identifier: 
      <%= text_field_tag :bill_identifier, "232323", :size => 10 %>      
    </p> 
    <p>sum: 
      <%= text_field_tag :sum, "123.40", :size => 10 %>      
    </p>
    <p>key: 
      <%= text_field_tag :key, "8800995566", :size => 10 %>      
    </p>
    <p>date: 
      <%= text_field_tag :date, Time.now.strftime("%Y-%m-%dT%H:%M:%S"), :size => 15 %>      
    </p>   
    
     
    <%= submit_tag "Send bill request" %>
  <% end %>
  
</fieldset>


<fieldset id="result">
  <legend>Bill search response</legend>
  <div id="xml-result"></div>  
</fieldset>



<style type="text/css">
  
  fieldset { 
    border: 1px solid blue;
    margin-top: 20px;
    padding: 10px;
    width: 40%;
    min-height: 50px; 
  }
  
  legend {
    padding: 3px;
  }
  
  input[type=submit] {
    width: 150px;
    float: right;
  }
      
  #result {
    position: relative;
    left: 400px;
    top: -270px;
    min-height: 230px;
  }
  
</style>

app/views/privat_gateway/send_request.js.erb
$("#xml-result").html("<%= escape_javascript(render(:partial => 'send_request')) %>");