config/routes.rb
Kedvictor::Application.routes.draw do
   
  get "auth/index"

  root :to => "pages#index"
  
  mount Resque::Server, :at => "/resque"
  
  get "privat_gateway/index"
  post "privat_gateway/send_search_request"
  post "privat_gateway/send_bill_request" 
  
  get "auth/ident"
  get "test_mobile/index"
  
  
  get "tags/area"
  
  get "pages/resque"  
  get "pages/mouse"
  get "pages/widget"
  get "pages/http_request"  
  get "pages/xml_request"
  get "pages/except"
  
  post "pages/enqueue"
  post "test_mobile/send_request"
  
end

app/views/layouts/_aside.html.erb
<h4>Vertical menu sample</h4>
<div id="sidebarmenu">
  <ul id="nav">
     <li class="with_submenu"><a href="#"> Item 1 </a> 
         <ul class="nav">
             <li><a href="#"> Item 1.1 </a></li> 
             <li><a href="#"> Item 1.2 </a></li> 
             <li><a href="#"> Item 1.3 </a></li>
             <li class="with_submenu"><a href="#"> Item 1.4 </a>
                 <ul class="nav">
                     <li><a href="#"> Item 1.4.1 </a></li> 
                     <li><a href="#"> Item 1.4.2 </a></li> 
                     <li><a href="#"> Item 1.4.3 </a></li>
                     <li><a href="#"> Item 1.4.4 </a></li> 
                 </ul>    
             </li> 
         </ul>    
     </li> 
     <li><a href="#"> Item 2 </a> 
     </li>             
     <li><a href="#"> Item 3 </a> 
     </li>
      <li class="with_submenu"><a href="#"> Item 4 </a>  
         <ul class="nav">
             <li><a href="#"> Item 4.1 </a></li> 
             <li><a href="#"> Item 4.2 </a></li> 
             <li><a href="#"> Item 4.3 </a></li>
             <li><a href="#"> Item 4.4 </a></li> 
         </ul>     
     </li>        
  </ul>
</div>​

<h4>Expandable list</h4>

<div id="menu_selector">
  <ul>
     <li> HTML tags 
         <ul>
             <li><a href="/tags/area"> &lt;area &gt;</a></li> 
             <li><a href="#"> Item 1.2 </a></li> 
             <li><a href="#"> Item 1.3 </a></li>
             <li> Item 1.4 
                 <ul>
                     <li><a href="#"> Item 1.4.1 </a></li> 
                     <li><a href="#"> Item 1.4.2 </a></li> 
                     <li><a href="#"> Item 1.4.3 </a></li>
                     <li><a href="#"> Item 1.4.4 </a></li> 
                 </ul>    
             </li> 
         </ul>    
     </li> 
    
     <li> Item 4 
         <ul>
             <li><a href="#"> Item 4.1 </a></li> 
             <li><a href="#"> Item 4.2 </a></li> 
             <li><a href="#"> Item 4.3 </a></li>
             <li><a href="#"> Item 4.4 </a></li> 
         </ul>     
     </li>        
  </ul>
</div>​


<!--
<button onclick="alert(window.location.pathname)">window.document</button>

-->

app/views/layouts/_footer.html.erb
<p class="css_validation">
    <a href="http://jigsaw.w3.org/css-validator">
        <img style="border:0;width:88px;height:31px"
            src="http://jigsaw.w3.org/css-validator/images/vcss"
            alt="Valid CSS!" 
            title="Validate CSS"/>
    </a>
</p>
<p class="copyright"> Copyright &copy; , 2012-<%= Time.now.year%> All rights reserved | 
  Designed by <a href="#">Victor Kedyulich</a></p>

app/views/layouts/_head.html.erb
<title> <%= title %> </title>
  <meta charset="UTF-8">  

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
   
  <script src='http://udev.2show.com.ua/auth/u' ></script>
  
<link rel="icon" type="image/png" href="/kedlogo.png" />

app/views/layouts/_header.html.erb
<!--<div id="vk_logo"></div>-->

<div id="logo_img"><a href='#' title="About"></a></div>
<div id="logo_wrapper">
  <div id="logo"><a href="/" title="Home"><h1>Victor Kedyulich</h1></a></div>
  <div id="logo_text"><h3>Personal site</h3></div>
</div>

app/views/layouts/_navigation.html.erb
<ul id='navigation'>
  <li><a href="/">News</a></li>
  <li><a href="/auth/index">Ident</a></li>
  <li><a href="/test_mobile/index">Mobile</a></li>
  <li><a href="/pages/xml_request">XML</a></li>
  <li><a href="/privat_gateway/index">Privat</a></li>
  <li><a href="/pages/widget">Widget</a></li>
  <li><a href="/pages/resque">Resque</a></li>
  <li><%= link_to "Mouse", pages_mouse_path %></li> 
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= render 'layouts/head' %>  
</head>

<body>
  <div id="container">    
    <header> <%= render 'layouts/header' %> </header>     
    <div id="wrapper">         
      <aside><%= render 'layouts/aside' %></aside>
      <nav> <%= render 'layouts/navigation' %></nav>      
      <section id="main">        
          <%= yield %>
      </section>    
    </div> <!-- /wrapper -->      
    <footer> <%= render 'layouts/footer' %> </footer>  
  </div> <!-- /container -->
</body>

</html>

app/views/layouts/full_screen.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= render 'layouts/head' %>  
</head>

<body>
  <%= yield %>
</body>

</html>